### ISSUE TITLE
tag uploads

### ISSUE THREAD

**Issue by umlaeute** [electrickery/pd-maxlib#1]
please tag all uploads to deken.

E.g. there's a [maxlib-1.5.8 upload](http://deken.puredata.info/info?url=http%3A%2F%2Fpuredata.info%2FMembers%2Ffjkraan%2Fsoftware%2Fmaxlib%2F1.5.8%2Fmaxlib%5Bv1.5.8%5D%28Sources%29.dek), but no corresponding tag in this repository.

**Comment by electrickery** [comment]
Fixed.
