### ISSUE TITLE
error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by fferri** [electrickery/pd-maxlib#4]
When building on macOS M1, it fails with:

src/subst.c:231:3: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                error("subst: %s: no such array", x->x_array->s_name);
                ^

**Comment by electrickery** [comment]
Thanks for the information. I plan to address this soon.
Greetings,
Fred Jan

**Comment by electrickery** [comment]
The compile error should be gone. The subst object seems to work like the original,  but it isn't completely clear what it should do. It seems to be a compositional tool inserting extra notes in intervals.

**Comment by fferri** [comment]
Thanks, now it builds fine!
